const AXIS_REMAP_X = 0x00
const AXIS_REMAP_Y = 0x01
const AXIS_REMAP_Z = 0x02
const AXIS_REMAP_POSITIVE = 0x00
const AXIS_REMAP_NEGATIVE = 0x01

// SIC registers
const BNO055_SIC_MATRIX_0_LSB_ADDR = 0X43
const BNO055_SIC_MATRIX_0_MSB_ADDR = 0X44
const BNO055_SIC_MATRIX_1_LSB_ADDR = 0X45
const BNO055_SIC_MATRIX_1_MSB_ADDR = 0X46
const BNO055_SIC_MATRIX_2_LSB_ADDR = 0X47
const BNO055_SIC_MATRIX_2_MSB_ADDR = 0X48
const BNO055_SIC_MATRIX_3_LSB_ADDR = 0X49
const BNO055_SIC_MATRIX_3_MSB_ADDR = 0X4A
const BNO055_SIC_MATRIX_4_LSB_ADDR = 0X4B
const BNO055_SIC_MATRIX_4_MSB_ADDR = 0X4C
const BNO055_SIC_MATRIX_5_LSB_ADDR = 0X4D
const BNO055_SIC_MATRIX_5_MSB_ADDR = 0X4E
const BNO055_SIC_MATRIX_6_LSB_ADDR = 0X4F
const BNO055_SIC_MATRIX_6_MSB_ADDR = 0X50
const BNO055_SIC_MATRIX_7_LSB_ADDR = 0X51
const BNO055_SIC_MATRIX_7_MSB_ADDR = 0X52
const BNO055_SIC_MATRIX_8_LSB_ADDR = 0X53
const BNO055_SIC_MATRIX_8_MSB_ADDR = 0X54

// Accelerometer Offset registers
const ACCEL_OFFSET_X_LSB_ADDR = 0X55
const ACCEL_OFFSET_X_MSB_ADDR = 0X56
const ACCEL_OFFSET_Y_LSB_ADDR = 0X57
const ACCEL_OFFSET_Y_MSB_ADDR = 0X58
const ACCEL_OFFSET_Z_LSB_ADDR = 0X59
const ACCEL_OFFSET_Z_MSB_ADDR = 0X5A

// Magnetometer Offset registers
const MAG_OFFSET_X_LSB_ADDR = 0X5B
const MAG_OFFSET_X_MSB_ADDR = 0X5C
const MAG_OFFSET_Y_LSB_ADDR = 0X5D
const MAG_OFFSET_Y_MSB_ADDR = 0X5E
const MAG_OFFSET_Z_LSB_ADDR = 0X5F
const MAG_OFFSET_Z_MSB_ADDR = 0X60

// Gyroscope Offset register s
const GYRO_OFFSET_X_LSB_ADDR = 0X61
const GYRO_OFFSET_X_MSB_ADDR = 0X62
const GYRO_OFFSET_Y_LSB_ADDR = 0X63
const GYRO_OFFSET_Y_MSB_ADDR = 0X64
const GYRO_OFFSET_Z_LSB_ADDR = 0X65
const GYRO_OFFSET_Z_MSB_ADDR = 0X66

// Radius registers
const ACCEL_RADIUS_LSB_ADDR = 0X67
const ACCEL_RADIUS_MSB_ADDR = 0X68
const MAG_RADIUS_LSB_ADDR = 0X69
const MAG_RADIUS_MSB_ADDR = 0X6A

// Power modes
const POWER_MODE_NORMAL = 0X00
const POWER_MODE_LOWPOWER = 0X01
const POWER_MODE_SUSPEND = 0X02

// Operation mode settings
const OPERATION_MODE_CONFIG = 0X00
const OPERATION_MODE_ACCONLY = 0X01
const OPERATION_MODE_MAGONLY = 0X02
const OPERATION_MODE_GYRONLY = 0X03
const OPERATION_MODE_ACCMAG = 0X04
const OPERATION_MODE_ACCGYRO = 0X05
const OPERATION_MODE_MAGGYRO = 0X06
const OPERATION_MODE_AMG = 0X07
const OPERATION_MODE_IMUPLUS = 0X08
const OPERATION_MODE_COMPASS = 0X09
const OPERATION_MODE_M4G = 0X0A
const OPERATION_MODE_NDOF_FMC_OFF = 0X0B
const OPERATION_MODE_NDOF = 0X0C